// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/infobloxopen/atlas-contacts-app/pkg/pb/contacts.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/infobloxopen/atlas-contacts-app/pkg/pb/contacts.proto

It has these top-level messages:
	Contact
	Email
	CreateContactRequest
	CreateContactResponse
	ReadContactRequest
	ReadContactResponse
	UpdateContactRequest
	UpdateContactResponse
	DeleteContactRequest
	ListContactsRequest
	ListContactsResponse
	SMSRequest
	ErrorContactRequest
	ErrorContactResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Contact struct {
	Id           uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName    string   `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName   string   `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	LastName     string   `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	PrimaryEmail string   `protobuf:"bytes,6,opt,name=primary_email,json=primaryEmail" json:"primary_email,omitempty"`
	Emails       []*Email `protobuf:"bytes,7,rep,name=emails" json:"emails,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Contact) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Contact) GetPrimaryEmail() string {
	if m != nil {
		return m.PrimaryEmail
	}
	return ""
}

func (m *Contact) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

type Email struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Email) Reset()                    { *m = Email{} }
func (m *Email) String() string            { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()               {}
func (*Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Email) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateContactRequest struct {
	Payload *Contact `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateContactRequest) Reset()                    { *m = CreateContactRequest{} }
func (m *CreateContactRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContactRequest) ProtoMessage()               {}
func (*CreateContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateContactRequest) GetPayload() *Contact {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateContactResponse struct {
	Result *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreateContactResponse) Reset()                    { *m = CreateContactResponse{} }
func (m *CreateContactResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateContactResponse) ProtoMessage()               {}
func (*CreateContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadContactRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadContactRequest) Reset()                    { *m = ReadContactRequest{} }
func (m *ReadContactRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadContactRequest) ProtoMessage()               {}
func (*ReadContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadContactRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadContactResponse struct {
	Result *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadContactResponse) Reset()                    { *m = ReadContactResponse{} }
func (m *ReadContactResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadContactResponse) ProtoMessage()               {}
func (*ReadContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateContactRequest struct {
	Payload *Contact `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateContactRequest) Reset()                    { *m = UpdateContactRequest{} }
func (m *UpdateContactRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateContactRequest) ProtoMessage()               {}
func (*UpdateContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateContactRequest) GetPayload() *Contact {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateContactResponse struct {
	Result *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UpdateContactResponse) Reset()                    { *m = UpdateContactResponse{} }
func (m *UpdateContactResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateContactResponse) ProtoMessage()               {}
func (*UpdateContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteContactRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteContactRequest) Reset()                    { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()               {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteContactRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListContactsRequest struct {
}

func (m *ListContactsRequest) Reset()                    { *m = ListContactsRequest{} }
func (m *ListContactsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListContactsRequest) ProtoMessage()               {}
func (*ListContactsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ListContactsResponse struct {
	Results []*Contact `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListContactsResponse) Reset()                    { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()               {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListContactsResponse) GetResults() []*Contact {
	if m != nil {
		return m.Results
	}
	return nil
}

type SMSRequest struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SMSRequest) Reset()                    { *m = SMSRequest{} }
func (m *SMSRequest) String() string            { return proto.CompactTextString(m) }
func (*SMSRequest) ProtoMessage()               {}
func (*SMSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SMSRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SMSRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ErrorContactRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ErrorContactRequest) Reset()                    { *m = ErrorContactRequest{} }
func (m *ErrorContactRequest) String() string            { return proto.CompactTextString(m) }
func (*ErrorContactRequest) ProtoMessage()               {}
func (*ErrorContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ErrorContactRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ErrorContactResponse struct {
}

func (m *ErrorContactResponse) Reset()                    { *m = ErrorContactResponse{} }
func (m *ErrorContactResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorContactResponse) ProtoMessage()               {}
func (*ErrorContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*Contact)(nil), "api.contacts.Contact")
	proto.RegisterType((*Email)(nil), "api.contacts.Email")
	proto.RegisterType((*CreateContactRequest)(nil), "api.contacts.CreateContactRequest")
	proto.RegisterType((*CreateContactResponse)(nil), "api.contacts.CreateContactResponse")
	proto.RegisterType((*ReadContactRequest)(nil), "api.contacts.ReadContactRequest")
	proto.RegisterType((*ReadContactResponse)(nil), "api.contacts.ReadContactResponse")
	proto.RegisterType((*UpdateContactRequest)(nil), "api.contacts.UpdateContactRequest")
	proto.RegisterType((*UpdateContactResponse)(nil), "api.contacts.UpdateContactResponse")
	proto.RegisterType((*DeleteContactRequest)(nil), "api.contacts.DeleteContactRequest")
	proto.RegisterType((*ListContactsRequest)(nil), "api.contacts.ListContactsRequest")
	proto.RegisterType((*ListContactsResponse)(nil), "api.contacts.ListContactsResponse")
	proto.RegisterType((*SMSRequest)(nil), "api.contacts.SMSRequest")
	proto.RegisterType((*ErrorContactRequest)(nil), "api.contacts.ErrorContactRequest")
	proto.RegisterType((*ErrorContactResponse)(nil), "api.contacts.ErrorContactResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Contacts service

type ContactsClient interface {
	Create(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error)
	Read(ctx context.Context, in *ReadContactRequest, opts ...grpc.CallOption) (*ReadContactResponse, error)
	Update(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error)
	Delete(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	List(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	ErrorExample(ctx context.Context, in *ErrorContactRequest, opts ...grpc.CallOption) (*ErrorContactResponse, error)
}

type contactsClient struct {
	cc *grpc.ClientConn
}

func NewContactsClient(cc *grpc.ClientConn) ContactsClient {
	return &contactsClient{cc}
}

func (c *contactsClient) Create(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error) {
	out := new(CreateContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Read(ctx context.Context, in *ReadContactRequest, opts ...grpc.CallOption) (*ReadContactResponse, error) {
	out := new(ReadContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Update(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error) {
	out := new(UpdateContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Delete(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) List(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/SendSMS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) ErrorExample(ctx context.Context, in *ErrorContactRequest, opts ...grpc.CallOption) (*ErrorContactResponse, error) {
	out := new(ErrorContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/ErrorExample", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contacts service

type ContactsServer interface {
	Create(context.Context, *CreateContactRequest) (*CreateContactResponse, error)
	Read(context.Context, *ReadContactRequest) (*ReadContactResponse, error)
	Update(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error)
	Delete(context.Context, *DeleteContactRequest) (*google_protobuf.Empty, error)
	List(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	SendSMS(context.Context, *SMSRequest) (*google_protobuf.Empty, error)
	ErrorExample(context.Context, *ErrorContactRequest) (*ErrorContactResponse, error)
}

func RegisterContactsServer(s *grpc.Server, srv ContactsServer) {
	s.RegisterService(&_Contacts_serviceDesc, srv)
}

func _Contacts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Create(ctx, req.(*CreateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Read(ctx, req.(*ReadContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Update(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Delete(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).List(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/SendSMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).SendSMS(ctx, req.(*SMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_ErrorExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).ErrorExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/ErrorExample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).ErrorExample(ctx, req.(*ErrorContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contacts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Contacts",
	HandlerType: (*ContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Contacts_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Contacts_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Contacts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Contacts_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Contacts_List_Handler,
		},
		{
			MethodName: "SendSMS",
			Handler:    _Contacts_SendSMS_Handler,
		},
		{
			MethodName: "ErrorExample",
			Handler:    _Contacts_ErrorExample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/infobloxopen/atlas-contacts-app/pkg/pb/contacts.proto",
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/atlas-contacts-app/pkg/pb/contacts.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 902 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x18, 0xd5, 0x3a, 0x66, 0x1d, 0x7f, 0x49, 0xd3, 0x30, 0x71, 0x5c, 0x67, 0x9b, 0x0a, 0x77, 0xca,
	0x4f, 0x14, 0xea, 0xdd, 0x62, 0xa2, 0x5c, 0xb8, 0x37, 0x25, 0xad, 0xa9, 0x40, 0xb4, 0x12, 0xb6,
	0x72, 0x53, 0x09, 0xa5, 0x63, 0xef, 0xc4, 0x99, 0xb2, 0xbb, 0x33, 0xec, 0x8c, 0xa1, 0x01, 0x55,
	0x02, 0x1e, 0x01, 0x6e, 0x78, 0x95, 0xf8, 0x8a, 0x67, 0x80, 0x27, 0x40, 0xe2, 0x86, 0xb7, 0x40,
	0x3b, 0x33, 0x1b, 0xdb, 0x1b, 0x27, 0x40, 0xc5, 0x9d, 0xfd, 0xcd, 0xf9, 0xbe, 0x73, 0xce, 0xcc,
	0xd9, 0x9d, 0x85, 0x07, 0x23, 0xa6, 0x4e, 0xc6, 0x03, 0x7f, 0xc8, 0xe3, 0x80, 0x25, 0xc7, 0x7c,
	0x10, 0xf1, 0x97, 0x5c, 0xd0, 0x24, 0x20, 0x2a, 0x22, 0xb2, 0x35, 0xe4, 0x89, 0x22, 0x43, 0x25,
	0x5b, 0x44, 0x88, 0x40, 0x7c, 0x39, 0x0a, 0xc4, 0x20, 0xc8, 0x6b, 0xbe, 0x48, 0xb9, 0xe2, 0x68,
	0x95, 0x08, 0xe6, 0xe7, 0x35, 0xef, 0xe6, 0x88, 0xf3, 0x51, 0x44, 0x03, 0xbd, 0x36, 0x18, 0x1f,
	0x07, 0x34, 0x16, 0xea, 0xd4, 0x40, 0xbd, 0x6d, 0xbb, 0x48, 0x04, 0x0b, 0x48, 0x92, 0x70, 0x45,
	0x14, 0xe3, 0x89, 0x1d, 0xe4, 0xdd, 0x9f, 0x91, 0x12, 0x9d, 0x1e, 0x2b, 0x33, 0x63, 0xd8, 0x1a,
	0xd1, 0xa4, 0xf5, 0x35, 0x89, 0x58, 0x48, 0x14, 0x0d, 0x2e, 0xfc, 0xb0, 0xcd, 0x77, 0x67, 0xc0,
	0xf2, 0x1b, 0x32, 0x1a, 0xd1, 0x34, 0xe0, 0x42, 0x8f, 0x5f, 0x40, 0xd5, 0xb9, 0xcc, 0xf5, 0xcc,
	0x94, 0x11, 0x4f, 0xe3, 0xf3, 0x11, 0xd9, 0x1f, 0xd3, 0x8b, 0xff, 0x70, 0xa0, 0xf2, 0xd0, 0xd8,
	0x45, 0x6b, 0x50, 0x62, 0x61, 0xc3, 0x69, 0x3a, 0x3b, 0xe5, 0x5e, 0x89, 0x85, 0xe8, 0x16, 0xc0,
	0x31, 0x4b, 0xa5, 0x3a, 0x4a, 0x48, 0x4c, 0x1b, 0xa5, 0xa6, 0xb3, 0x53, 0xed, 0x55, 0x75, 0xe5,
	0x29, 0x89, 0x29, 0x7a, 0x0b, 0x56, 0x62, 0x16, 0x86, 0x11, 0x35, 0xeb, 0x4b, 0x7a, 0x1d, 0x4c,
	0x49, 0x03, 0x6e, 0x42, 0x35, 0x22, 0x79, 0x7b, 0x59, 0x2f, 0x2f, 0x67, 0x05, 0xbd, 0xb8, 0x07,
	0xd7, 0x44, 0xca, 0x62, 0x92, 0x9e, 0x1e, 0xd1, 0x98, 0xb0, 0xa8, 0xe1, 0x66, 0x80, 0x83, 0xeb,
	0x93, 0xb3, 0xad, 0xd2, 0xba, 0x33, 0xf9, 0xeb, 0xd7, 0xa5, 0x72, 0x5a, 0x7a, 0xee, 0xf4, 0x56,
	0x2d, 0xaa, 0x9b, 0x81, 0xd0, 0xfb, 0xe0, 0x6a, 0xb4, 0x6c, 0x54, 0x9a, 0x4b, 0x3b, 0x2b, 0xed,
	0x0d, 0x7f, 0xf6, 0xbc, 0x7c, 0x0d, 0xea, 0x59, 0x48, 0xc7, 0xcd, 0x66, 0x2d, 0x3b, 0xf8, 0x07,
	0x07, 0xde, 0x30, 0xed, 0x45, 0x87, 0xfb, 0x50, 0x21, 0x61, 0x98, 0x52, 0x29, 0x8d, 0xbd, 0x83,
	0xed, 0xc9, 0xd9, 0xd6, 0x75, 0xb8, 0x96, 0x6d, 0x50, 0x07, 0x1f, 0x3e, 0xfd, 0xe4, 0xf3, 0xc3,
	0x2e, 0x9e, 0x6a, 0xc9, 0xc1, 0x9d, 0x7b, 0x93, 0xb3, 0xad, 0xbb, 0xcb, 0x0e, 0x42, 0x50, 0x1e,
	0x70, 0x1e, 0x21, 0x60, 0xf2, 0xc8, 0xea, 0x44, 0x35, 0x70, 0xc7, 0x2c, 0x51, 0xfb, 0x7b, 0x08,
	0xec, 0xc6, 0x1e, 0xb1, 0x10, 0x3f, 0x86, 0xda, 0xc3, 0x94, 0x12, 0x45, 0x6d, 0xad, 0x47, 0xbf,
	0x1a, 0x53, 0xa9, 0x50, 0x00, 0x15, 0x41, 0x4e, 0x23, 0x4e, 0x8c, 0xac, 0x95, 0xf6, 0xe6, 0xbc,
	0xa3, 0x1c, 0x9e, 0xa3, 0xf0, 0xc7, 0xb0, 0x59, 0x18, 0x24, 0x05, 0x4f, 0x24, 0x45, 0x2d, 0x70,
	0x53, 0x2a, 0xc7, 0x91, 0xba, 0x7a, 0x90, 0x05, 0xe1, 0xb7, 0x01, 0xf5, 0x28, 0x09, 0x0b, 0x72,
	0x0a, 0x1b, 0x84, 0x1f, 0xc1, 0xc6, 0x1c, 0xea, 0xf5, 0xb8, 0x1e, 0x43, 0xed, 0x50, 0x84, 0xff,
	0x8f, 0xf9, 0xc2, 0xa0, 0xd7, 0x13, 0xf4, 0x2e, 0xd4, 0x1e, 0xd1, 0x88, 0x5e, 0x10, 0x54, 0xb4,
	0xbf, 0x09, 0x1b, 0x9f, 0x31, 0xa9, 0x2c, 0x4a, 0x5a, 0x58, 0xe6, 0x67, 0xbe, 0x6c, 0x55, 0x04,
	0x50, 0x31, 0x04, 0xb2, 0xe1, 0xe8, 0x78, 0x5e, 0xe6, 0xc7, 0xa2, 0xf0, 0x3e, 0x40, 0xff, 0x49,
	0xff, 0x12, 0x76, 0xd4, 0x80, 0x4a, 0x4c, 0xa5, 0x24, 0xa3, 0xfc, 0xe1, 0xcb, 0xff, 0xe2, 0x77,
	0x60, 0xa3, 0x9b, 0xa6, 0x3c, 0xfd, 0x07, 0xf9, 0x75, 0xa8, 0xcd, 0xc3, 0x8c, 0xce, 0xf6, 0xf7,
	0x2e, 0x2c, 0xe7, 0xe2, 0x51, 0x0c, 0xae, 0x09, 0x14, 0xc2, 0x05, 0xb5, 0x0b, 0xf2, 0xea, 0xdd,
	0xb9, 0x12, 0x63, 0xe6, 0x63, 0xef, 0xc7, 0xdf, 0xff, 0xfc, 0xb9, 0x54, 0xc3, 0xd5, 0xf3, 0xb7,
	0x6b, 0x27, 0x3f, 0x42, 0x34, 0x84, 0x72, 0x96, 0x28, 0xd4, 0x9c, 0x1f, 0x74, 0x31, 0x8b, 0xde,
	0xed, 0x2b, 0x10, 0x96, 0xa8, 0xae, 0x89, 0xd6, 0xd1, 0xda, 0x39, 0x51, 0xf0, 0x1d, 0x0b, 0x5f,
	0xa1, 0x6f, 0xc1, 0x35, 0x39, 0x29, 0x7a, 0x5a, 0x14, 0xc3, 0xa2, 0xa7, 0x85, 0x09, 0xc3, 0xef,
	0x69, 0xaa, 0xdb, 0x5e, 0x7d, 0x86, 0xca, 0x7a, 0xf2, 0x59, 0xf8, 0x6a, 0x6a, 0x90, 0x81, 0x6b,
	0xb2, 0x55, 0xe4, 0x5e, 0x94, 0x38, 0xaf, 0xee, 0x9b, 0x5b, 0xc4, 0xcf, 0xaf, 0x18, 0xbf, 0x9b,
	0x5d, 0x31, 0xf8, 0xce, 0xe4, 0x6c, 0xab, 0x7a, 0xfe, 0x6a, 0x36, 0x36, 0x77, 0x8b, 0x36, 0x9f,
	0x43, 0x39, 0xcb, 0x21, 0x2a, 0xec, 0xd4, 0x82, 0xc8, 0x7a, 0xf8, 0x2a, 0x88, 0xb5, 0xf8, 0xa6,
	0xa6, 0x59, 0x41, 0xd3, 0x63, 0x43, 0xcf, 0xa0, 0xd2, 0xa7, 0x49, 0xd8, 0x7f, 0xd2, 0x47, 0x8d,
	0xf9, 0x09, 0xd3, 0xdc, 0x5e, 0xea, 0xe1, 0x96, 0x9e, 0x77, 0x03, 0xa3, 0x79, 0xd9, 0x81, 0x8c,
	0x65, 0xc7, 0xd9, 0x45, 0x12, 0x56, 0x75, 0x3a, 0xbb, 0x2f, 0x49, 0x2c, 0x22, 0x5a, 0x74, 0xb1,
	0x20, 0xe0, 0x45, 0x17, 0x8b, 0xc2, 0x8d, 0xb7, 0x35, 0x6b, 0x1d, 0xd5, 0x0a, 0xac, 0x34, 0x03,
	0x7b, 0xf6, 0x4e, 0x38, 0xf8, 0xcd, 0xf9, 0xe9, 0xa3, 0x5f, 0x1c, 0x94, 0x4c, 0x1f, 0x04, 0xfc,
	0x05, 0xac, 0x7d, 0xca, 0x4f, 0x92, 0xe6, 0x01, 0x8d, 0x48, 0x4c, 0x52, 0x36, 0x44, 0xed, 0x13,
	0xa5, 0x84, 0xec, 0x04, 0xc1, 0xbf, 0xff, 0xac, 0xf0, 0x6e, 0xbc, 0x18, 0xe4, 0xfd, 0x0f, 0x72,
	0x6c, 0xd6, 0xd8, 0x5e, 0xfa, 0xc0, 0xbf, 0xb7, 0x5b, 0x72, 0x4a, 0xed, 0x75, 0x22, 0x44, 0xc4,
	0x86, 0xfa, 0x0a, 0x0f, 0x5e, 0x48, 0x9e, 0x74, 0x2e, 0x54, 0x9e, 0xed, 0xfd, 0xe7, 0x0f, 0x99,
	0xfb, 0x62, 0x30, 0x70, 0xf5, 0x01, 0x7c, 0xf8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x68,
	0x61, 0x4e, 0x07, 0x09, 0x00, 0x00,
}
